development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  # url: <%= ENV.fetch("REDIS_TLS_URL") { "redis://localhost:6379/1" } %>
  # url: <% ENV.fetch("REDIS_TLS_URL") %>
  url: <%= ENV["REDIS_TLS_URL"] %>
  # url: ENV['REDIS_TLS_URL']
  # channel_prefix: dronie_backend_production
